# Generated by Django 5.2.10 on 2026-01-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
